---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saleor

resources:
  - namespace.yml
  - ./infra
  - ./db
  - ./jaeger
  - ./mailhog
  - ./redis
  - ../../../saleor/deployment/kustomize
  - ../../../saleor-dashboard/deployment/kustomize
  - ../../../react-storefront/deployment/kustomize
