apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: db-secret
    envs:
      - db.env

configMapGenerator:
  - name: db-replica-user
    files:
      - replica_user.sql
