---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  template:
    spec:
      hostname: jaeger
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
            - containerPort: 16686
              name: jaeger-ui
            - containerPort: 14268
            - containerPort: 9411


