---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    spec:
      containers:
      - name: redis
        image: redis:5.0-alpine
        resources:
          requests:
            cpu: "10m"
            memory: "128Mi"
           
        ports:
          - containerPort: 6379
            name: redis-port
        volumeMounts:
          - mountPath: /data
            name: redis-volume
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: redis
