---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
spec:
  template:
    spec:
      containers:
        - name: mailhog
          image: mailhog/mailhog
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 1025
              name: mailhog-smtp
            - containerPort: 8025
              name: mailhog-ui


