---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saleor

commonLabels:
  app: saleor-platform


resources:
  - ../../base
  - ./saleor-dashboard
  - infra/ingress.yml

patchesStrategicMerge:
  - infra/storage-class-gp3.yml
  - saleor/saleor-api.yml
  - saleor-dashboard/saleor-dashboard.yml

configMapGenerator:
  - name: saleor-env
    behavior: replace
    envs:
      - config/backend.env
      - config/common.env

secretGenerator:
  - name: saleor-rsa-key
    behavior: replace
    files:
      - config/private.pem
  - name: saleor-secret
    behavior: replace
    envs:
      - config/secret.env
  - name: db-secret
    behavior: replace
    envs:
      - config/db.env
